export const VILLAGE_SETUP = 'VILLAGE_SETUP'
export const VOLUNTEER_SETUP = 'VOLUNTEER_SETUP'
export const VOLUNTEER_SUCCESS = 'VOLUNTEER_SUCCESS'

export const HOUSEHOLD_SETUP = 'HOUSEHOLD_SETUP'
export const HOUSEHOLD_SUCCESS = 'HOUSEHOLD_SUCCESS'
export const USERDATA_SETUP = 'USERDATA_SETUP'
export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const REPORTS = 'REPORTS'



